language: java
jdk:
- oraclejdk8
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: n5HF/uYeOqkWoH091sQ+OHrL87f+/VXwA+UaHCrFlgJ1BUbkaqzxgdn4lhNmsorR4hUzbtwIMM8XgvIFfhvoE/MbRZ3xXSEJFI/oayTVgY7Pl/MZrtO//w7NnU5jvFQoq3dGJOHcj9/07ZzV838KCUx3BRfsHIpW3KYSBn2Atechyg6n3YxnZUX81ND8efaghVa9haF6v5mDZrz4FlJ7GO7NwNkAbgw+vM0yc1eoJ4l0YdKgOCfgmbRjxSSZb8cDPIZNYOj6a/hiX19glFoPaOq2lLNpomJBwS6kYjqrsY+AfVoqSU4c3aEaBUUMgTR7cc1m7FGIGVhfYKvZwa/SGBj0myFvggOsbpTd0C6yVywBDBClAExZXTo4SEkioo2hBtEQ1OhMHbeElW1XA+cxACkct8I+uWJMsa55Xr4Z5h4oBTUUFV15q2ihsZ4AskzO5JaZ/Xg7sRtgrcTp+4NZFHRaN4/YDm80Aa4oPflkMiXhPK1g9vQ2RWwIw7fOXwrOgRlDRNsceXS4QxHsSSq+WowlTlfj7j2GJLukoonfc2U9V3WP64tuVz0uc58Z8OXWQeeFRRrbrzaBfiQ8GS7g7D1PWd1JWUXpH4LStGCaPC/RGexAlSLFPVoYkv9II7SLZc4vL8TSN+x2gmEYaVnDlx7qPRl4W/7uuAiGi0kICDA=
  app: dokumen-tazkia
  on:
    repo: idtazkia/pelayanan-dokumen
